---
globs:
  - '!.claude/**'
  - '!.cursorrules'
  - '!.cursor/rules/**'
  - '!**/node_modules'
  - '!.specstory/**'
  - '!.ai/**'
  - '!AGENTS.md'
  - '!CLAUDE.md'
  - '!.opencode/**'
  - '!.config/opencode/**'
