#!/bin/bash
# This hook is run after a new virtualenv is activated.

# Automatically create a project directory if the current directory is named
# "Projects". Set up future calls to workon to change to the project directory.
# Based on
# https://github.com/dcrosta/dotfiles/blob/master/virtualenvs/postmkvirtualenv

if [[ `basename "$MKVIRTUALENV_PWD"` != "Projects" ]]; then
  exit 0
fi

projdir=$MKVIRTUALENV_PWD/$(basename "$VIRTUAL_ENV")

postactivate=$VIRTUAL_ENV/$VIRTUALENVWRAPPER_ENV_BIN_DIR/postactivate

[ -z "$postactivate" ] && exit 0;

echo "cd \"$projdir\"" >> "$postactivate"
echo                   >> "$postactivate"

if [ ! -e "$projdir" ]; then
  mkdir -p "$projdir"
fi

_project=$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME
if [ ! -e "$_project" ]; then
  if [[ "$HOST_OS" == "mingw" ]]; then
    cmd //c echo "$projdir" > "$_project"
  else
    echo "$projdir" > "$_project"
  fi
fi

cd "$projdir"

unset postactivate projdir _project
