#!/usr/bin/env bash
##
# Bash aliases
#
# vim:set filetype=sh:

# Alias git to hub if hub is installed.
if [ -n "$(command -v hub)" ]; then
  alias git=hub
fi

# ~/.dotfiles is a bare Git repo with the work directory set to ~
alias .dotfiles='GIT_DIR=$HOME/.dotfiles GIT_WORK_TREE=$HOME'

# Launch OpenCode rooted at the dotfiles bare-repo dir to avoid AFT plugin
# `configure` timeouts caused by ripgrep walking macOS-sandboxed paths under
# $HOME (~/Library/*, FileProvider iCloud mounts).
alias dotfiles-opencode='cd "$HOME/.dotfiles" && GIT_DIR="$HOME/.dotfiles" GIT_WORK_TREE="$HOME" opencode'

LSCMD='ls'
if [[ "$HOST_OS" == "darwin" ]]; then
  # https://www.gnu.org/software/coreutils/
  command_exists gdircolors && alias dircolors='gdircolors'
  command_exists gfind && alias find='gfind'
  command_exists gsort && alias sort='gsort'
  command_exists gstat && alias stat='gstat'
  command_exists gls && LSCMD='gls'
fi

if command_exists lsd; then
  LSCMD='lsd' # See https://github.com/Peltoche/lsd
elif command_exists exa; then
  LSCMD='exa' # See https://github.com/ogham/exa
fi

# shellcheck disable=SC2139
alias ls="LC_COLLATE=C ${LSCMD} --color=auto --group-directories-first"
unset LSCMD

# From OMZ
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'
