#!/bin/sh
#
# Based on
# https://github.com/bjeanes/dot-files/blob/master/vcs/git/git_template/hooks/ctags,
# which is based off of
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e

command -v ctags > /dev/null 2>&1 || exit 0

new_tags=.git/tags.$$
ctags --tag-relative -Rf $new_tags --exclude=.git --languages=-javascript,sql
mv $new_tags .git/tags
