#!/bin/sh
#
# Based on
# https://github.com/bjeanes/dot-files/blob/master/vcs/git/git_template/hooks/ctags,
# which is based off of
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e

command -v ctags > /dev/null 2>&1 || exit 0

# Use the directory above the hooks directory as the location to store tags so that
# we can tag from submodules (the hooks/ folder is under <submodule name>/, not .git/).
hook_dir=`dirname $0`
git_dir=`dirname $hook_dir`
tags=$git_dir/tags
temp_tags=$tags.$$

if [[ "$1" == "append" ]]; then
  cp "$tags" "$temp_tags"
  append_opt="-a"
fi

ctags $append_opt --tag-relative -Rf "$temp_tags" --exclude=.git --languages=-sql
mv "$temp_tags" "$tags"
