# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

'on':
  push:
    branches: [main]
  schedule:
    - cron: '37 04 * * *' # 4:37 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@149be573ed167efe00af8441a647cdb2247fac33 # v4.14.2
