# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

'on':
  push:
    branches: [main]
  schedule:
    - cron: '37 04 * * *' # 4:37 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@7cdb7496c5b9c7c7fdf706e3cc0bf8163ca61927 # v4.13.9
